import robby
#import numpy as np
from utils import *
import random
POSSIBLE_ACTIONS = ["MoveNorth", "MoveSouth", "MoveEast", "MoveWest", "StayPut", "PickUpCan", "MoveRandom"]
rw = robby.World(10, 10)
rw.graphicsOff()


def sortByFitness(genomes):
    tuples = [(fitness(g), g) for g in genomes]
    tuples.sort()
    sortedFitnessValues = [f for (f, g) in tuples]
    sortedGenomes = [g for (f, g) in tuples]
    return sortedGenomes, sortedFitnessValues


def randomGenome(length):
    """
    :param length:
    :return: string, random integers between 0 and 6 inclusive
    """

    """Your Code Here"""
    count=0
    gen=""
    while count<length:
        gen=gen+str(random.randint(0,6))
        count+=1

    return gen



def makePopulation(size, length):
    """
    :param size - of population:
    :param length - of genome
    :return: list of length size containing genomes of length length
    """


    """Your Code Here"""
    pop=[]
    count=0
    while count<size:
        pop.append(randomGenome(length))
        count+=1

    return pop

def fitness(genome, steps=200, init=0.50):
    """

    :param genome: to test
    :param steps: number of steps in the cleaning session
    :param init: amount of cans
    :return:
    """
    if type(genome) is not str or len(genome) != 243:
        raise Exception("strategy is not a string of length 243")
    for char in genome:
        if char not in "0123456":
            raise Exception("strategy contains a bad character: '%s'" % char)
    if type(steps) is not int or steps < 1:
        raise Exception("steps must be an integer > 0")
    if type(init) is str:
        # init is a config file
        rw.load(init)
    elif type(init) in [int, float] and 0 <= init <= 1:
        # init is a can density
        rw.goto(0, 0)
        rw.distributeCans(init)
    else:
        raise Exception("invalid initial configuration")

    fit=0
    for i in range(0,25):
        rw.goto(0, 0)
        rw.distributeCans(init)
        for ii in range(0,steps):
            we=rw.getPerceptCode()
            direction=""
            if genome[we]=="0":
                direction="MoveNorth"
            elif genome[we]=="1":
                direction="MoveSouth"
            elif genome[we]=="2":
                direction="MoveEast"
            elif genome[we]=="3":
                direction="MoveWest"
            elif genome[we]=="4":
                direction="StayPut"
            elif genome[we]=="5":
                direction="PickUpCan"
            elif genome[we]=="6":
                direction="MoveRandom"
            fit+=int(rw.performAction(direction))
    return fit/25


def evaluateFitness(population):
    """
    :param population:
    :return: a pair of values: the average fitness of the population as a whole and the fitness of the best individual
    in the population.
    """
    best=(0,0)
    aver=0
    count=len(population)
    for i in range(0,count):
        fit=0
        parent=population[i]
        par=str(parent)
        fit+=fitness(parent)
        if best[0]<fit:
            best=(fit,i)
        aver+=fit

    aver=aver/count
    return aver,best


def crossover(genome1, genome2):
    """
    :param genome1:
    :param genome2:
    :return: two new genomes produced by crossing over the given genomes at a random crossover point.
    """
    chi1=""
    chi2=""
    ran=random.randint(1,len(genome1)-1)

    gen1=str(genome1)
    gen2=str(genome2)
    for i in range(0,len(genome1)):
        if i<=ran:
            chi1=chi1+gen1[i]
            chi2=chi2+gen2[i]
        else:
            chi1=chi1+gen2[i]
            chi2=chi2+gen1[i]

    return chi1,chi2


def mutate(genome, mutationRate):
    """
    :param genome:
    :param mutationRate:
    :return: a new mutated version of the given genome.
    """
    end=""
    gen=str(genome)
    for i in range(0,len(genome)):
        randy2=random.uniform(0,1)

        if randy2<mutationRate:
            c=gen[i]
            randy=random.randint(0,6)
            while randy==c:
                randy=random.randint(0,6)
            end=end+str(randy)
        else:
            end=end+gen[i]
    return end

def selectPair(population):
    """

    :param population:
    :return: two genomes from the given population using fitness-proportionate selection.
    This function should use RankSelection,
    """
    rank=[]
    for i in range(0,len(population)):
        rank.append(i)
    eee=weightedChoice(population,rank)
    eee2=weightedChoice(population,rank)

    return eee, eee2


def runGA(populationSize, crossoverRate, mutationRate, logFile=""):
    """

    :param populationSize: :param crossoverRate: :param mutationRate: :param logFile: :return: xt file in which to
    store the data generated by the GA, for plotting purposes. When the GA terminates, this function should return
    the generation at which the string of all ones was found.is the main GA program, which takes the population size,
    crossover rate (pc), and mutation rate (pm) as parameters. The optional logFile parameter is a string specifying
    the name of a te
    """
    f=open(logFile,"w+")
    rw.graphicsOff()
    length=243
    generation=300
    print("Population Size: {}".format(populationSize))
    print("Genome Length: {}".format(length))

    b=-999.99
    population=makePopulation(populationSize,length)
    for i in range(0,generation+1):
        newPop,weight=sortByFitness(population)
        for j in range(0,len(population)-1,2):
            e1,e2=selectPair(newPop)
            population[j]=e1
            population[j+1]=e2
            population[j]=mutate(population[j],mutationRate)
            population[j+1]=mutate(population[j+1],mutationRate)
            randy=random.uniform(0,1)
            if crossoverRate<randy:
                c1,c2=crossover(population[j],population[j+1])
                population[j]=c1
                population[j+1]=c2
        best=weight[len(weight)-1]
        aver=0
        for pew in range(0,len(newPop)):
            aver+=weight[pew]
        aver=aver/len(newPop)

        if b<best:
            b=float(best)
        print("Generation {}: Average Fitness {}, Best Fitness {}".format(i,aver,b))
        if i%10==0:
            print("{}, {}, {}".format(b,aver,i))
            bee=0
            ree=0
            f.write("%f %f %f %s \n" % (i,aver,b,newPop[len(newPop)-1]))
        
    f.close()
    return None


def test_FitnessFunction():
    f = fitness(rw.strategyM)
    print("Fitness for StrategyM : {0}".format(f))



#test_FitnessFunction()

runGA(100, 0.1, 0.01, "GAoutput.txt")